# Generated by Django 5.1.1 on 2024-12-04 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DietaryRestriction",
            fields=[
                ("restriction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "restriction",
                    models.CharField(default="Default Restriction", max_length=50),
                ),
            ],
            options={
                "db_table": "dietary_restriction",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("menu_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "menu",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("restaurant_id", models.AutoField(primary_key=True, serialize=False)),
                ("restaurant_name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("website_link", models.URLField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "restaurant",
            },
        ),
        migrations.CreateModel(
            name="MenuSection",
            fields=[
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                ("section", models.CharField(max_length=100)),
                (
                    "section_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.menu",
                    ),
                ),
            ],
            options={
                "db_table": "menu_section",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=100)),
                (
                    "item_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.menusection",
                    ),
                ),
            ],
            options={
                "db_table": "menu_item",
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("operation_type", models.CharField(max_length=20)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("operation_status", models.CharField(max_length=10)),
                ("operation_time_stamp", models.DateTimeField(auto_now_add=True)),
                ("error_description", models.TextField(blank=True, null=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.menu",
                    ),
                ),
            ],
            options={
                "db_table": "processing_log",
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_management.restaurant",
            ),
        ),
        migrations.CreateModel(
            name="MenuItemDietaryRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dietary_restrictions",
                        to="menu_management.menuitem",
                    ),
                ),
                (
                    "restriction",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="menu_management.dietaryrestriction",
                    ),
                ),
            ],
            options={
                "db_table": "menu_item_dietary_restriction",
                "unique_together": {("item", "restriction")},
            },
        ),
    ]
