# Generated by Django 5.1.1 on 2024-12-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_id",
            field=models.AutoField(
                db_column="restaurant_id", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="restaurant_id",
            new_name="id",
        ),
    ]
