# Generated by Django 5.1.2 on 2024-12-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_management", "0002_alter_restaurant_restaurant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
